### PR TITLE
Code cleanup for PR

### PR DESCRIPTION
**Pull request by nicodv**
Hi Ian,

Thanks for the PR! Wasn't aware people were using this on _millions_ of rows, very cool. May I ask the field of application, for my curiosity?

I went through your code and it looks good. You missed one function call in `kprototypes.py`, but this PR fixes that. Also, the function now explicitly returns `centroids` instead of updating in-place, and I did some minor refactoring for clarity.

Thanks for contributing!
Nico

### CODE REVIEW

**Comment by NuclearFishin** [comment]
Hey Nico, thanks for putting the finishing touches on the code. The field I'm applying your algorithm to is retail sales analysis, so k-prototypes is a good fit due to the mixed numerical / categorical nature of such data. The project is ongoing so if I find any more improvements I'll be sure to send more PRs :) Cheers!

**Comment by nicodv** [comment]
Ah, very cool. BTW, in what order of magnitude is the speed increase you're seeing for this?

Hhhmmm... I think I did something wrong with `git`. This way or merging makes you not show up as a contributor.

**Comment by NuclearFishin** [comment]
Hey Nico, I guess the speed increase is relative to the size of the sample data. Technically, I don't think the algorithmic complexity has changed, but practically it's doing a lot less unnecessary work. Here's a Jupyter notebook showing some before/after benchmarking of the optimisation:

https://dl.dropboxusercontent.com/u/7721832/K-modes%20Benchmarking.html

You can see that the 'curve' is much shallower for the optimised version.

No worries with how the merge turned out, I'm just happy to have made a contribution :)

**Comment by nicodv** [comment]
Great work, that's a pretty significant speed increase!

I might release this as part of v0.5 soon.

Cheers,
Nico

**Comment by nicodv** [comment]
FYI, part of the just released v0.5

**Comment by NuclearFishin** [comment]
Awesome, thanks Nico! :)

**Pull request merged**
